const ENV = process.env.REACT_APP_ENV || 'local';
const LOCAL_ENV = 'local';
const DEVELOPMENT_ENV = 'dev';
const LOCAL_REDIRECT_URI = process.env.REACT_APP_LOCAL_REDIRECT_URI;
const DEV_REDIRECT_URI = process.env.REACT_APP_DEV_REDIRECT_URI;
const REDIRECT_URI = ENV === LOCAL_ENV ? LOCAL_REDIRECT_URI : DEV_REDIRECT_URI;
const INFURA_API_KEY = process.env.REACT_APP_INFURA_API_KEY;
const INFURA_API_SECRET_KEY = process.env.REACT_APP_INFURA_API_SECRET_KEY;

const CONSTANTS = {
  ENV,
  LOCAL_ENV,
  DEVELOPMENT_ENV,
  REDIRECT_URI,
  INFURA_API_KEY,
  INFURA_API_SECRET_KEY,
};

export default CONSTANTS;
